AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CREATEFOO:
    Type: AWS::IAM::User
    Properties: 
      Groups: 
        - Dev
      LoginProfile: 
        Password: mypassword1984@
      UserName: foo
    DependsOn: NestedStack

  NestedStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: https://assignment-codix-1.s3.amazonaws.com/cfn-nested-stack.yaml
      TimeoutInMinutes: '60'
